---
# tasks file for role_infiniband
- name: Check if iblinkinfo is available.
  ansible.builtin.shell:
    cmd: iblinkinfo
  register: ib_installed
  ignore_errors: true
  changed_when: false

- name: Install dependencies.
  ansible.builtin.apt:
    name:
      - debhelper
      - libgfortran4
      - libnl-route-3-dev
      - libnl-route-3-dev
      - libnl-3-dev
      - gfortran
      - graphviz
      - quilt
      - autoconf
      - bison
      - gcc
      - tcl
      - autotools-dev
      - flex
      - chrpath
      - pkg-config
      - libnl-route-3-200
      - tk
      - swig
      - make
      - m4
      - dpatch
      - automake
      - dkms
      - libltdl-dev
    state: present
    update_cache: true
  when: ib_installed is failed
  retries: 3

- name: Download infiniband driver.
  ansible.builtin.get_url:
    url: "https://content.mellanox.com/ofed/MLNX_OFED-5.8-2.0.3.0/MLNX_OFED_LINUX-5.8-2.0.3.0-ubuntu22.04-x86_64.tgz"
    dest: "/root/MLNX_OFED_LINUX-5.8-2.0.3.0-ubuntu22.04-x86_64.tgz"
  when: ib_installed is failed
  retries: 3

- name: Extract infiniband driver.
  ansible.builtin.unarchive:
    src: "/root/MLNX_OFED_LINUX-5.8-2.0.3.0-ubuntu22.04-x86_64.tgz"
    dest: "/root/"
  when: ib_installed is failed

- name: Install infiniband driver.
  ansible.builtin.shell:
    cmd: "./mlnxofedinstall -q"
    chdir: "/root/MLNX_OFED_LINUX-5.8-2.0.3.0-ubuntu22.04-x86_64.tgz"
  when: ib_installed is failed

- name: Restart openibd
  ansible.builtin.command: /etc/init.d/openibd restart
  register: openib_output
  when: ib_installed is failed

- name: Output from restart openib.
  ansible.builtin.debug:
    msg: "{{ openib_output.stdout_lines }}"
  when: ib_installed is failed

# permissions for /dev/infiniband/umad0 to 666?
- name: Configure netplan.
  block:
    - name: Get infiniband interace name.
      ansible.builtin.shell:
        cmd: ip a | grep ib | head -n 1
      register: infiniband_interface

    - name: Edit /etc/netplan/infiniband.yaml
      ansible.builtin.blockinfile:
        create: yes
        insertbefore: "version: 2"
        path: /etc/netplan/infiniband.yaml
        block: |
          network:
            version: 2
            ethernets:
              {{ infiniband_interface.stdout.split(":")[1] | trim }}:
                critical: false
                addresses:
                - {{ ansible_default_ipv4.address.split(".")[0] }}.{{ ansible_default_ipv4.address.split(".")[1] }}.{{ ansible_default_ipv4.address.split(".")[2] | int + ip_add }}.{{ ansible_default_ipv4.address.split(".")[3] }}/{{ ip_subnet | string }}

    - name: Apply netplan.
      ansible.builtin.shell:
        cmd: netplan apply

- name: Get iblinkinfo.
  ansible.builtin.shell:
    cmd: iblinkinfo
  register: ib_out

- name: Print iblinkinfoi output.
  ansible.builtin.debug:
    msg: "{{ ib_out.stdout_lines }}"

- name: Get ip a.
  ansible.builtin.shell:
    cmd: ip a
  register: ip_out

- name: Print iblinkinfoi output.
  ansible.builtin.debug:
    msg: "{{ ip_out.stdout_lines }}"
